// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: doctor.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const completeTokenStatus = `-- name: CompleteTokenStatus :exec
UPDATE Token
SET status = 'COMPLETED'
WHERE st_id = ? AND visit_date = CURRENT_DATE AND doc_id = ? AND status = 'WAITING'
`

type CompleteTokenStatusParams struct {
	StID  int32 `json:"st_id"`
	DocID int32 `json:"doc_id"`
}

func (q *Queries) CompleteTokenStatus(ctx context.Context, arg CompleteTokenStatusParams) error {
	_, err := q.db.ExecContext(ctx, completeTokenStatus, arg.StID, arg.DocID)
	return err
}

const getDoctorByID = `-- name: GetDoctorByID :one
SELECT doc_id, name, specialization, contact, password
FROM Doctor
WHERE doc_id = ?
`

func (q *Queries) GetDoctorByID(ctx context.Context, docID int32) (Doctor, error) {
	row := q.db.QueryRowContext(ctx, getDoctorByID, docID)
	var i Doctor
	err := row.Scan(
		&i.DocID,
		&i.Name,
		&i.Specialization,
		&i.Contact,
		&i.Password,
	)
	return i, err
}

const getDoctorQueueToday = `-- name: GetDoctorQueueToday :many
SELECT
    t.token_id,
    t.visit_date,
    TIME_FORMAT(t.visit_time, '%H:%i') AS visit_time,
    t.status,
    s.st_id,
    s.name AS student_name,
    s.dept,
    s.contact
FROM Token t
JOIN Student s ON t.st_id = s.st_id
WHERE t.visit_date = CURRENT_DATE
  AND t.doc_id = ?
  AND t.status = 'WAITING'
ORDER BY t.token_id ASC
`

type GetDoctorQueueTodayRow struct {
	TokenID     int32          `json:"token_id"`
	VisitDate   time.Time      `json:"visit_date"`
	VisitTime   string         `json:"visit_time"`
	Status      string         `json:"status"`
	StID        int32          `json:"st_id"`
	StudentName string         `json:"student_name"`
	Dept        sql.NullString `json:"dept"`
	Contact     sql.NullString `json:"contact"`
}

func (q *Queries) GetDoctorQueueToday(ctx context.Context, docID int32) ([]GetDoctorQueueTodayRow, error) {
	rows, err := q.db.QueryContext(ctx, getDoctorQueueToday, docID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDoctorQueueTodayRow
	for rows.Next() {
		var i GetDoctorQueueTodayRow
		if err := rows.Scan(
			&i.TokenID,
			&i.VisitDate,
			&i.VisitTime,
			&i.Status,
			&i.StID,
			&i.StudentName,
			&i.Dept,
			&i.Contact,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
