// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Contain struct {
	PID          int32          `json:"p_id"`
	MedicineName string         `json:"medicine_name"`
	MedicineType string         `json:"medicine_type"`
	Dosage       sql.NullString `json:"dosage"`
}

type Doctor struct {
	DocID          int32  `json:"doc_id"`
	Name           string `json:"name"`
	Specialization string `json:"specialization"`
	Contact        string `json:"contact"`
}

type Medicine struct {
	MedicineName string         `json:"medicine_name"`
	MedicineType string         `json:"medicine_type"`
	Manufacturer sql.NullString `json:"manufacturer"`
}

type PreSymptom struct {
	PID     int32  `json:"p_id"`
	Symptom string `json:"symptom"`
}

type Prescription struct {
	PID   int32        `json:"p_id"`
	PDate sql.NullTime `json:"p_date"`
	StID  int32        `json:"st_id"`
	DocID int32        `json:"doc_id"`
}

type Require struct {
	PID        int32          `json:"p_id"`
	TestName   string         `json:"test_name"`
	TestDate   sql.NullTime   `json:"test_date"`
	TestResult sql.NullString `json:"test_result"`
}

type Student struct {
	StID       int32          `json:"st_id"`
	Name       string         `json:"name"`
	Gender     string         `json:"gender"`
	Contact    sql.NullString `json:"contact"`
	Dept       sql.NullString `json:"dept"`
	Dob        sql.NullTime   `json:"dob"`
	BloodGroup sql.NullString `json:"blood_group"`
}

type Test struct {
	TestName string `json:"test_name"`
	TestFee  string `json:"test_fee"`
}

type Token struct {
	TokenID   int32     `json:"token_id"`
	VisitDate time.Time `json:"visit_date"`
	VisitTime time.Time `json:"visit_time"`
	StID      int32     `json:"st_id"`
}
