// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prescription.sql

package db

import (
	"context"
	"database/sql"
)

const addPrescribedMedicine = `-- name: AddPrescribedMedicine :exec
INSERT INTO Contain (p_id, medicine_name, medicine_type, dosage)
VALUES (?, ?, ?, ?)
`

type AddPrescribedMedicineParams struct {
	PID          int32          `json:"p_id"`
	MedicineName string         `json:"medicine_name"`
	MedicineType string         `json:"medicine_type"`
	Dosage       sql.NullString `json:"dosage"`
}

func (q *Queries) AddPrescribedMedicine(ctx context.Context, arg AddPrescribedMedicineParams) error {
	_, err := q.db.ExecContext(ctx, addPrescribedMedicine,
		arg.PID,
		arg.MedicineName,
		arg.MedicineType,
		arg.Dosage,
	)
	return err
}

const addRequiredTest = `-- name: AddRequiredTest :exec
INSERT INTO Requires (p_id, test_name)
VALUES (?, ?)
`

type AddRequiredTestParams struct {
	PID      int32  `json:"p_id"`
	TestName string `json:"test_name"`
}

func (q *Queries) AddRequiredTest(ctx context.Context, arg AddRequiredTestParams) error {
	_, err := q.db.ExecContext(ctx, addRequiredTest, arg.PID, arg.TestName)
	return err
}

const addSymptom = `-- name: AddSymptom :exec
INSERT INTO Pre_symptoms (p_id, symptom)
VALUES (?, ?)
`

type AddSymptomParams struct {
	PID     int32  `json:"p_id"`
	Symptom string `json:"symptom"`
}

func (q *Queries) AddSymptom(ctx context.Context, arg AddSymptomParams) error {
	_, err := q.db.ExecContext(ctx, addSymptom, arg.PID, arg.Symptom)
	return err
}

const createPrescription = `-- name: CreatePrescription :execresult
INSERT INTO Prescription (st_id, doc_id)
VALUES (?, ?)
`

type CreatePrescriptionParams struct {
	StID  int32 `json:"st_id"`
	DocID int32 `json:"doc_id"`
}

func (q *Queries) CreatePrescription(ctx context.Context, arg CreatePrescriptionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPrescription, arg.StID, arg.DocID)
}

const getAllMedicines = `-- name: GetAllMedicines :many
SELECT medicine_name, medicine_type, manufacturer FROM Medicine ORDER BY medicine_name ASC
`

func (q *Queries) GetAllMedicines(ctx context.Context) ([]Medicine, error) {
	rows, err := q.db.QueryContext(ctx, getAllMedicines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medicine
	for rows.Next() {
		var i Medicine
		if err := rows.Scan(&i.MedicineName, &i.MedicineType, &i.Manufacturer); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTests = `-- name: GetAllTests :many
SELECT test_name, test_fee FROM Test ORDER BY test_name ASC
`

func (q *Queries) GetAllTests(ctx context.Context) ([]Test, error) {
	rows, err := q.db.QueryContext(ctx, getAllTests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Test
	for rows.Next() {
		var i Test
		if err := rows.Scan(&i.TestName, &i.TestFee); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrescriptionDetails = `-- name: GetPrescriptionDetails :one
SELECT p.p_id, p.p_date, s.st_id, s.name AS student_name, s.dept, s.blood_group, d.name AS doctor_name, d.specialization
FROM Prescription p
JOIN Student s ON p.st_id = s.st_id
JOIN Doctor d ON p.doc_id = d.doc_id
WHERE p.p_id = ?
`

type GetPrescriptionDetailsRow struct {
	PID            int32          `json:"p_id"`
	PDate          sql.NullTime   `json:"p_date"`
	StID           int32          `json:"st_id"`
	StudentName    string         `json:"student_name"`
	Dept           sql.NullString `json:"dept"`
	BloodGroup     sql.NullString `json:"blood_group"`
	DoctorName     string         `json:"doctor_name"`
	Specialization string         `json:"specialization"`
}

func (q *Queries) GetPrescriptionDetails(ctx context.Context, pID int32) (GetPrescriptionDetailsRow, error) {
	row := q.db.QueryRowContext(ctx, getPrescriptionDetails, pID)
	var i GetPrescriptionDetailsRow
	err := row.Scan(
		&i.PID,
		&i.PDate,
		&i.StID,
		&i.StudentName,
		&i.Dept,
		&i.BloodGroup,
		&i.DoctorName,
		&i.Specialization,
	)
	return i, err
}

const getPrescriptionMedicines = `-- name: GetPrescriptionMedicines :many
SELECT m.medicine_name, m.medicine_type, c.dosage
FROM Contain c
JOIN Medicine m ON c.medicine_name = m.medicine_name AND c.medicine_type = m.medicine_type
WHERE c.p_id = ?
`

type GetPrescriptionMedicinesRow struct {
	MedicineName string         `json:"medicine_name"`
	MedicineType string         `json:"medicine_type"`
	Dosage       sql.NullString `json:"dosage"`
}

func (q *Queries) GetPrescriptionMedicines(ctx context.Context, pID int32) ([]GetPrescriptionMedicinesRow, error) {
	rows, err := q.db.QueryContext(ctx, getPrescriptionMedicines, pID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPrescriptionMedicinesRow
	for rows.Next() {
		var i GetPrescriptionMedicinesRow
		if err := rows.Scan(&i.MedicineName, &i.MedicineType, &i.Dosage); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrescriptionSymptoms = `-- name: GetPrescriptionSymptoms :many
SELECT symptom FROM Pre_symptoms WHERE p_id = ?
`

func (q *Queries) GetPrescriptionSymptoms(ctx context.Context, pID int32) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getPrescriptionSymptoms, pID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var symptom string
		if err := rows.Scan(&symptom); err != nil {
			return nil, err
		}
		items = append(items, symptom)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentLabResults = `-- name: GetStudentLabResults :many
SELECT r.p_id, r.test_name, r.test_date, r.test_result, p.p_date
FROM Requires r
JOIN Prescription p ON r.p_id = p.p_id
WHERE p.st_id = ?
ORDER BY p.p_date DESC
`

type GetStudentLabResultsRow struct {
	PID        int32          `json:"p_id"`
	TestName   string         `json:"test_name"`
	TestDate   sql.NullTime   `json:"test_date"`
	TestResult sql.NullString `json:"test_result"`
	PDate      sql.NullTime   `json:"p_date"`
}

func (q *Queries) GetStudentLabResults(ctx context.Context, stID int32) ([]GetStudentLabResultsRow, error) {
	rows, err := q.db.QueryContext(ctx, getStudentLabResults, stID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStudentLabResultsRow
	for rows.Next() {
		var i GetStudentLabResultsRow
		if err := rows.Scan(
			&i.PID,
			&i.TestName,
			&i.TestDate,
			&i.TestResult,
			&i.PDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentPrescriptionHistory = `-- name: GetStudentPrescriptionHistory :many
SELECT p.p_id, p.p_date, d.name AS doctor_name, d.specialization
FROM Prescription p
JOIN Doctor d ON p.doc_id = d.doc_id
WHERE p.st_id = ?
ORDER BY p.p_date DESC
`

type GetStudentPrescriptionHistoryRow struct {
	PID            int32        `json:"p_id"`
	PDate          sql.NullTime `json:"p_date"`
	DoctorName     string       `json:"doctor_name"`
	Specialization string       `json:"specialization"`
}

func (q *Queries) GetStudentPrescriptionHistory(ctx context.Context, stID int32) ([]GetStudentPrescriptionHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getStudentPrescriptionHistory, stID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStudentPrescriptionHistoryRow
	for rows.Next() {
		var i GetStudentPrescriptionHistoryRow
		if err := rows.Scan(
			&i.PID,
			&i.PDate,
			&i.DoctorName,
			&i.Specialization,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
