// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prescription.sql

package db

import (
	"context"
	"database/sql"
)

const addPrescribedMedicine = `-- name: AddPrescribedMedicine :exec
INSERT INTO Contain (p_id, medicine_name, medicine_type, dosage)
VALUES (?, ?, ?, ?)
`

type AddPrescribedMedicineParams struct {
	PID          int32          `json:"p_id"`
	MedicineName string         `json:"medicine_name"`
	MedicineType string         `json:"medicine_type"`
	Dosage       sql.NullString `json:"dosage"`
}

func (q *Queries) AddPrescribedMedicine(ctx context.Context, arg AddPrescribedMedicineParams) error {
	_, err := q.db.ExecContext(ctx, addPrescribedMedicine,
		arg.PID,
		arg.MedicineName,
		arg.MedicineType,
		arg.Dosage,
	)
	return err
}

const addRequiredTest = `-- name: AddRequiredTest :exec
INSERT INTO Requires (p_id, test_name)
VALUES (?, ?)
`

type AddRequiredTestParams struct {
	PID      int32  `json:"p_id"`
	TestName string `json:"test_name"`
}

func (q *Queries) AddRequiredTest(ctx context.Context, arg AddRequiredTestParams) error {
	_, err := q.db.ExecContext(ctx, addRequiredTest, arg.PID, arg.TestName)
	return err
}

const addSymptom = `-- name: AddSymptom :exec
INSERT INTO Pre_symptoms (p_id, symptom)
VALUES (?, ?)
`

type AddSymptomParams struct {
	PID     int32  `json:"p_id"`
	Symptom string `json:"symptom"`
}

func (q *Queries) AddSymptom(ctx context.Context, arg AddSymptomParams) error {
	_, err := q.db.ExecContext(ctx, addSymptom, arg.PID, arg.Symptom)
	return err
}

const createPrescription = `-- name: CreatePrescription :execresult
INSERT INTO Prescription (st_id, doc_id)
VALUES (?, ?)
`

type CreatePrescriptionParams struct {
	StID  int32 `json:"st_id"`
	DocID int32 `json:"doc_id"`
}

func (q *Queries) CreatePrescription(ctx context.Context, arg CreatePrescriptionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPrescription, arg.StID, arg.DocID)
}

const getPrescriptionDetails = `-- name: GetPrescriptionDetails :one
SELECT p.p_id, p.p_date, s.st_id, s.name AS student_name, s.dept, s.blood_group, d.name AS doctor_name, d.specialization
FROM Prescription p
JOIN Student s ON p.st_id = s.st_id
JOIN Doctor d ON p.doc_id = d.doc_id
WHERE p.p_id = ?
`

type GetPrescriptionDetailsRow struct {
	PID            int32          `json:"p_id"`
	PDate          sql.NullTime   `json:"p_date"`
	StID           int32          `json:"st_id"`
	StudentName    string         `json:"student_name"`
	Dept           sql.NullString `json:"dept"`
	BloodGroup     sql.NullString `json:"blood_group"`
	DoctorName     string         `json:"doctor_name"`
	Specialization string         `json:"specialization"`
}

func (q *Queries) GetPrescriptionDetails(ctx context.Context, pID int32) (GetPrescriptionDetailsRow, error) {
	row := q.db.QueryRowContext(ctx, getPrescriptionDetails, pID)
	var i GetPrescriptionDetailsRow
	err := row.Scan(
		&i.PID,
		&i.PDate,
		&i.StID,
		&i.StudentName,
		&i.Dept,
		&i.BloodGroup,
		&i.DoctorName,
		&i.Specialization,
	)
	return i, err
}

const getPrescriptionMedicines = `-- name: GetPrescriptionMedicines :many
SELECT m.medicine_name, m.medicine_type, c.dosage
FROM Contain c
JOIN Medicine m ON c.medicine_name = m.medicine_name AND c.medicine_type = m.medicine_type
WHERE c.p_id = ?
`

type GetPrescriptionMedicinesRow struct {
	MedicineName string         `json:"medicine_name"`
	MedicineType string         `json:"medicine_type"`
	Dosage       sql.NullString `json:"dosage"`
}

func (q *Queries) GetPrescriptionMedicines(ctx context.Context, pID int32) ([]GetPrescriptionMedicinesRow, error) {
	rows, err := q.db.QueryContext(ctx, getPrescriptionMedicines, pID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPrescriptionMedicinesRow
	for rows.Next() {
		var i GetPrescriptionMedicinesRow
		if err := rows.Scan(&i.MedicineName, &i.MedicineType, &i.Dosage); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrescriptionSymptoms = `-- name: GetPrescriptionSymptoms :many
SELECT symptom FROM Pre_symptoms WHERE p_id = ?
`

func (q *Queries) GetPrescriptionSymptoms(ctx context.Context, pID int32) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getPrescriptionSymptoms, pID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var symptom string
		if err := rows.Scan(&symptom); err != nil {
			return nil, err
		}
		items = append(items, symptom)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
