// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	AddPrescribedMedicine(ctx context.Context, arg AddPrescribedMedicineParams) error
	AddRequiredTest(ctx context.Context, arg AddRequiredTestParams) error
	AddSymptom(ctx context.Context, arg AddSymptomParams) error
	CreatePrescription(ctx context.Context, arg CreatePrescriptionParams) (sql.Result, error)
	GenerateToken(ctx context.Context, arg GenerateTokenParams) error
	GetNextTokenIDForToday(ctx context.Context, visitDate time.Time) (interface{}, error)
	GetPrescriptionDetails(ctx context.Context, pID int32) (GetPrescriptionDetailsRow, error)
	GetPrescriptionMedicines(ctx context.Context, pID int32) ([]GetPrescriptionMedicinesRow, error)
	GetPrescriptionSymptoms(ctx context.Context, pID int32) ([]string, error)
	GetStudentByID(ctx context.Context, stID int32) (Student, error)
	GetTodayTokens(ctx context.Context) ([]GetTodayTokensRow, error)
}

var _ Querier = (*Queries)(nil)
