// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reception.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createStudent = `-- name: CreateStudent :exec
INSERT INTO Student (st_id, name, gender, contact, dept, dob, blood_group)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateStudentParams struct {
	StID       int32          `json:"st_id"`
	Name       string         `json:"name"`
	Gender     string         `json:"gender"`
	Contact    sql.NullString `json:"contact"`
	Dept       sql.NullString `json:"dept"`
	Dob        sql.NullTime   `json:"dob"`
	BloodGroup sql.NullString `json:"blood_group"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) error {
	_, err := q.db.ExecContext(ctx, createStudent,
		arg.StID,
		arg.Name,
		arg.Gender,
		arg.Contact,
		arg.Dept,
		arg.Dob,
		arg.BloodGroup,
	)
	return err
}

const generateToken = `-- name: GenerateToken :exec
INSERT INTO Token (token_id, visit_date, visit_time, st_id, doc_id, status)
VALUES (?, CURRENT_DATE, CURRENT_TIME, ?, ?, 'WAITING')
`

type GenerateTokenParams struct {
	TokenID int32 `json:"token_id"`
	StID    int32 `json:"st_id"`
	DocID   int32 `json:"doc_id"`
}

func (q *Queries) GenerateToken(ctx context.Context, arg GenerateTokenParams) error {
	_, err := q.db.ExecContext(ctx, generateToken, arg.TokenID, arg.StID, arg.DocID)
	return err
}

const getAllDoctors = `-- name: GetAllDoctors :many
SELECT doc_id, name, specialization, contact
FROM Doctor
ORDER BY name ASC
`

type GetAllDoctorsRow struct {
	DocID          int32  `json:"doc_id"`
	Name           string `json:"name"`
	Specialization string `json:"specialization"`
	Contact        string `json:"contact"`
}

func (q *Queries) GetAllDoctors(ctx context.Context) ([]GetAllDoctorsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllDoctors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllDoctorsRow
	for rows.Next() {
		var i GetAllDoctorsRow
		if err := rows.Scan(
			&i.DocID,
			&i.Name,
			&i.Specialization,
			&i.Contact,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNextTokenIDForToday = `-- name: GetNextTokenIDForToday :one
SELECT COALESCE(MAX(token_id) + 1, 1)
FROM Token
WHERE visit_date = CURRENT_DATE
`

func (q *Queries) GetNextTokenIDForToday(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getNextTokenIDForToday)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getStudentByID = `-- name: GetStudentByID :one
SELECT st_id, name, gender, contact, dept, dob, blood_group
FROM Student
WHERE st_id = ?
`

func (q *Queries) GetStudentByID(ctx context.Context, stID int32) (Student, error) {
	row := q.db.QueryRowContext(ctx, getStudentByID, stID)
	var i Student
	err := row.Scan(
		&i.StID,
		&i.Name,
		&i.Gender,
		&i.Contact,
		&i.Dept,
		&i.Dob,
		&i.BloodGroup,
	)
	return i, err
}

const getTodayTokens = `-- name: GetTodayTokens :many
SELECT
    t.token_id,
    t.visit_date,
    TIME_FORMAT(t.visit_time, '%H:%i') AS visit_time,
    t.status,
    s.st_id,
    s.name AS student_name,
    s.dept,
    s.contact,
    d.doc_id,
    d.name AS doctor_name,
    d.specialization
FROM Token t
JOIN Student s ON t.st_id = s.st_id
JOIN Doctor d ON t.doc_id = d.doc_id
WHERE t.visit_date = CURRENT_DATE
ORDER BY t.token_id ASC
`

type GetTodayTokensRow struct {
	TokenID        int32          `json:"token_id"`
	VisitDate      time.Time      `json:"visit_date"`
	VisitTime      string         `json:"visit_time"`
	Status         string         `json:"status"`
	StID           int32          `json:"st_id"`
	StudentName    string         `json:"student_name"`
	Dept           sql.NullString `json:"dept"`
	Contact        sql.NullString `json:"contact"`
	DocID          int32          `json:"doc_id"`
	DoctorName     string         `json:"doctor_name"`
	Specialization string         `json:"specialization"`
}

func (q *Queries) GetTodayTokens(ctx context.Context) ([]GetTodayTokensRow, error) {
	rows, err := q.db.QueryContext(ctx, getTodayTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTodayTokensRow
	for rows.Next() {
		var i GetTodayTokensRow
		if err := rows.Scan(
			&i.TokenID,
			&i.VisitDate,
			&i.VisitTime,
			&i.Status,
			&i.StID,
			&i.StudentName,
			&i.Dept,
			&i.Contact,
			&i.DocID,
			&i.DoctorName,
			&i.Specialization,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTokenStatus = `-- name: UpdateTokenStatus :exec
UPDATE Token
SET status = ?
WHERE token_id = ? AND visit_date = CURRENT_DATE
`

type UpdateTokenStatusParams struct {
	Status  string `json:"status"`
	TokenID int32  `json:"token_id"`
}

func (q *Queries) UpdateTokenStatus(ctx context.Context, arg UpdateTokenStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTokenStatus, arg.Status, arg.TokenID)
	return err
}
