// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const generateToken = `-- name: GenerateToken :exec
INSERT INTO Token (token_id, visit_date, visit_time, st_id)
VALUES (?, ?, ?, ?)
`

type GenerateTokenParams struct {
	TokenID   int32     `json:"token_id"`
	VisitDate time.Time `json:"visit_date"`
	VisitTime time.Time `json:"visit_time"`
	StID      int32     `json:"st_id"`
}

func (q *Queries) GenerateToken(ctx context.Context, arg GenerateTokenParams) error {
	_, err := q.db.ExecContext(ctx, generateToken,
		arg.TokenID,
		arg.VisitDate,
		arg.VisitTime,
		arg.StID,
	)
	return err
}

const getNextTokenIDForToday = `-- name: GetNextTokenIDForToday :one
SELECT COALESCE(MAX(token_id) + 1, 1)
FROM Token
WHERE visit_date = ?
`

func (q *Queries) GetNextTokenIDForToday(ctx context.Context, visitDate time.Time) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getNextTokenIDForToday, visitDate)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getStudentByID = `-- name: GetStudentByID :one
SELECT st_id, name, gender, contact, dept, dob, blood_group
FROM Student
WHERE st_id = ?
`

func (q *Queries) GetStudentByID(ctx context.Context, stID int32) (Student, error) {
	row := q.db.QueryRowContext(ctx, getStudentByID, stID)
	var i Student
	err := row.Scan(
		&i.StID,
		&i.Name,
		&i.Gender,
		&i.Contact,
		&i.Dept,
		&i.Dob,
		&i.BloodGroup,
	)
	return i, err
}

const getTodayTokens = `-- name: GetTodayTokens :many
SELECT t.token_id, t.visit_date, t.visit_time, s.st_id, s.name AS student_name, s.dept, s.contact
FROM Token t
JOIN Student s ON t.st_id = s.st_id
WHERE t.visit_date = CURRENT_DATE
ORDER BY t.token_id ASC
`

type GetTodayTokensRow struct {
	TokenID     int32          `json:"token_id"`
	VisitDate   time.Time      `json:"visit_date"`
	VisitTime   time.Time      `json:"visit_time"`
	StID        int32          `json:"st_id"`
	StudentName string         `json:"student_name"`
	Dept        sql.NullString `json:"dept"`
	Contact     sql.NullString `json:"contact"`
}

func (q *Queries) GetTodayTokens(ctx context.Context) ([]GetTodayTokensRow, error) {
	rows, err := q.db.QueryContext(ctx, getTodayTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTodayTokensRow
	for rows.Next() {
		var i GetTodayTokensRow
		if err := rows.Scan(
			&i.TokenID,
			&i.VisitDate,
			&i.VisitTime,
			&i.StID,
			&i.StudentName,
			&i.Dept,
			&i.Contact,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
