// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vault.sql

package db

import (
	"context"
	"database/sql"
)

const getPrescriptionFullHeader = `-- name: GetPrescriptionFullHeader :one
SELECT p.p_id, p.p_date,
       s.st_id, s.name AS student_name, s.dept, s.gender, s.blood_group, s.dob,
       d.name AS doctor_name, d.specialization, d.contact AS doctor_contact
FROM Prescription p
JOIN Student s ON p.st_id = s.st_id
JOIN Doctor d ON p.doc_id = d.doc_id
WHERE p.p_id = ?
`

type GetPrescriptionFullHeaderRow struct {
	PID            int32          `json:"p_id"`
	PDate          sql.NullTime   `json:"p_date"`
	StID           int32          `json:"st_id"`
	StudentName    string         `json:"student_name"`
	Dept           sql.NullString `json:"dept"`
	Gender         string         `json:"gender"`
	BloodGroup     sql.NullString `json:"blood_group"`
	Dob            sql.NullTime   `json:"dob"`
	DoctorName     string         `json:"doctor_name"`
	Specialization string         `json:"specialization"`
	DoctorContact  string         `json:"doctor_contact"`
}

func (q *Queries) GetPrescriptionFullHeader(ctx context.Context, pID int32) (GetPrescriptionFullHeaderRow, error) {
	row := q.db.QueryRowContext(ctx, getPrescriptionFullHeader, pID)
	var i GetPrescriptionFullHeaderRow
	err := row.Scan(
		&i.PID,
		&i.PDate,
		&i.StID,
		&i.StudentName,
		&i.Dept,
		&i.Gender,
		&i.BloodGroup,
		&i.Dob,
		&i.DoctorName,
		&i.Specialization,
		&i.DoctorContact,
	)
	return i, err
}

const getPrescriptionLabTests = `-- name: GetPrescriptionLabTests :many
SELECT r.test_name, r.test_date, r.test_result, t.test_fee
FROM Requires r
JOIN Test t ON r.test_name = t.test_name
WHERE r.p_id = ?
`

type GetPrescriptionLabTestsRow struct {
	TestName   string         `json:"test_name"`
	TestDate   sql.NullTime   `json:"test_date"`
	TestResult sql.NullString `json:"test_result"`
	TestFee    string         `json:"test_fee"`
}

func (q *Queries) GetPrescriptionLabTests(ctx context.Context, pID int32) ([]GetPrescriptionLabTestsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPrescriptionLabTests, pID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPrescriptionLabTestsRow
	for rows.Next() {
		var i GetPrescriptionLabTestsRow
		if err := rows.Scan(
			&i.TestName,
			&i.TestDate,
			&i.TestResult,
			&i.TestFee,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentPrescriptionList = `-- name: GetStudentPrescriptionList :many
SELECT p.p_id, p.p_date, d.name AS doctor_name, d.specialization
FROM Prescription p
JOIN Doctor d ON p.doc_id = d.doc_id
WHERE p.st_id = ?
ORDER BY p.p_date DESC, p.p_id DESC
`

type GetStudentPrescriptionListRow struct {
	PID            int32        `json:"p_id"`
	PDate          sql.NullTime `json:"p_date"`
	DoctorName     string       `json:"doctor_name"`
	Specialization string       `json:"specialization"`
}

func (q *Queries) GetStudentPrescriptionList(ctx context.Context, stID int32) ([]GetStudentPrescriptionListRow, error) {
	rows, err := q.db.QueryContext(ctx, getStudentPrescriptionList, stID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStudentPrescriptionListRow
	for rows.Next() {
		var i GetStudentPrescriptionListRow
		if err := rows.Scan(
			&i.PID,
			&i.PDate,
			&i.DoctorName,
			&i.Specialization,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
